2 image upload
youngxpepp/relay_08 pull request #4
Opened 2020-08-14 13:56 UTC by Yejikwon

## return value 변경했습니다!

2020-08-14 14:19 UTC, youngxpepp requested changes

2020-08-14 14:19 UTC, youngxpepp commented on server/src/image/ImageController.ts
> +        return idValue.imageId;
response dto가 있어야 할 것 같은데요?ㅠㅠ
이렇게 하면 반환 값이 숫자 하나만 오지 않아요?

2020-08-14 14:47 UTC, Yejikwon commented on server/src/image/ImageController.ts
> +        return idValue.imageId;
헛!! 감사합니다!!! 다시 수정하겠습니다

2020-08-14 15:11 UTC, Yejikwon commented on server/src/image/ImageController.ts
> +        return idValue.imageId;
수정했습니다~! 나중에 시간되실 때 한번만 다시 확인부탁드려요!
(꼼꼼하게 봐주셔서 감사합니다 ㅠ)

- base64 인코딩된 데이터도 잘 들어가지는 부분 캡처본입니다.
  - ![image](https://user-images.githubusercontent.com/13073517/90264245-c549f400-de8b-11ea-8417-e56c5f4b3f97.png)

2020-08-15 05:15 UTC, youngxpepp approved these changes
고생하셨습니당

2020-08-15 06:07 UTC, merged